### ISSUE TITLE
Debugging and source maps

### ISSUE THREAD

**Issue by iboutsikas** [ghost-fvtt/foundry-factory#85]
I am trying to debug my module (along with it's interactions with dnd5e, but that's another story) and I cannot get any breakpoints to bind from vscode. If I put the exact same breakpoint through chrome itself, vscode will stop as well there. But not the other way around. The sourcemaps are generated and are in `dist/`. Could this be an issue with symlinking to the foundry modules directory?

OS: Windows
Preset: ghost's Gulp + Rollup Preset (with Typescript + SCSS)

**Comment by ghost91-** [comment]
Hi @iboutsikas, thanks for the report!

Can you post the `launch.json` you are using? Mine looks like this and it works fine:
```json5
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "pwa-chrome",
            "request": "launch",
            "runtimeExecutable": "/usr/bin/chromium",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:30000/game",
            "webRoot": "${workspaceFolder}/dist"
        }
    ]
}
```
The key point is that the `webRoot` needs to be set correctly. I have been told that The way I am doing it is actually wrong, and that I should be using `pathMapping` instead of setting the `webRoot` to my dist folder. This is what it would look like:
```json5
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "pwa-chrome",
            "request": "launch",
            "runtimeExecutable": "/usr/bin/chromium",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:30000/game",
            "webRoot": "/path/to/the/foundry/instance/resources/app/public",
            "pathMapping": {
                "/<systems / modules, depending on what you have
>/ds4": "${workspaceFolder}/dist"
            }
        }
    ]
}
```
I just tested this and it also works fine for me.

**Comment by ghost91-** [comment]
Closing this due to lack of feedback and not being able to reproduce the problem.
